### ISSUE TITLE
Free GPU and system memory

### ISSUE THREAD

**Issue by HedgehogCode** [CSBDeep/CSBDeep_fiji#10]
Tobias Boothe reported that if the plugin is executed in a loop the GPU memory will grow full and at some point, you have to restart Fiji.

**Comment by HedgehogCode** [comment]
@frauzufall can you test it, or should I set up an environment where I can test it?

**Comment by frauzufall** [comment]
Hey @HedgehogCode, thanks for all the work! and sorry for me not being very responsive right now. I am refactoring the code whenever I got some time to make it better readable, I will add your changes to my version as well and create a PR to discuss as soon as possible. We should also talk about if some part of our work should go into `imagej-tensorflow`.
