### ISSUE TITLE
Run plugin from command line

### ISSUE THREAD

**Issue by HedgehogCode** [CSBDeep/CSBDeep_fiji#13]
Running the plugin from the command line doesn't work because the result isn't shown until clicking somewhere with the mouse.

Example script:
```
cd /path/to/Fiji.app
./ImageJ-linux64 --ij2 -macro ~/CARE_denoise.ijm
```

Example macro:
```
open("~/image.tif");
run("3D Denoising - Planaria", "datasetview=net.imagej.display.DefaultDatasetView@6ca6979e ntiles=16 overlap=32");
selectWindow("result");
saveAs("Tiff", "~/image_denoised.tif");
run("Quit");
```

@tboo, thank you for reporting this bug!

**Comment by frauzufall** [comment]
Should not be an issue anymore. There is also an [example script](https://github.com/CSBDeep/CSBDeep_fiji/blob/master/script/CARE_generic.py).
