### ISSUE TITLE
Putting JAR on maven central

### ISSUE THREAD

**Issue by haesleinhuepf** [CSBDeep/CSBDeep_fiji#15]
Hey CSBDeep friends,

would it be possible to make this repository available as maven dependency on maven central?

Cheers,
Robert

**Comment by hadim** [comment]
Looks like it's already the case: http://maven.imagej.net/#nexus-search;quick~csbdeep

**Comment by haesleinhuepf** [comment]
Cool, thanks for the headsup! I guess @frauzufall did it.

Thanks!
