### ISSUE TITLE
Make progress dialog invisible

### ISSUE THREAD

**Issue by haesleinhuepf** [CSBDeep/CSBDeep_fiji#18]
Hey guys,

may it be possible to hide the progress dialog? We would like to run the plugin in the background subsequently and a popping up progress window might annoy the user.

Thanks!
Robert

**Comment by frauzufall** [comment]
Good idea! Should work now, use `"showProgressDialog": false` when calling a CSBDeep command to hide the dialog and reopen this issue if it does not work as intended,
