### ISSUE TITLE
GPU support on Windows

### ISSUE THREAD

**Issue by frauzufall** [CSBDeep/CSBDeep_fiji#24]
We need to add installation instructions for Windows GPU support (and also update the ones for Linux).

Until we finish the PR to TensorFlow automatically loading the GPU or CPU lib depending on what is supported, the workaround is to manually add the native GPU TensorFlow library to Fiji.

Here is an update site that should do this for Windows:

https://sites.imagej.net/CSBDeep-GPU-win64-TF1.12.0

In Linux I also have to add CUDA to my PATH and LD_LIBRARY_PATH environment variables, something similar might have to be done for Windows:
```
export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}} 
```

Could someone on Windows with a recent CUDA installation add this update site additionally to the default CSBDeep update site and try if it works or what else needs to be done (e.g. environment variables)?

I would update the documentation then asap.

**Comment by maweigert** [comment]
Just tested it on Windows 7, Cuda 9.0, Cudnn 7.3 and after activating the update site everything runs on the GPU (without any path adjustments), woohoo! Well done!

**Comment by frauzufall** [comment]
Cool, thanks for testing!

I also updated the [Wiki install page](https://github.com/CSBDeep/CSBDeep_website/wiki/CSBDeep-in-Fiji-%E2%80%93-Installation) at least a bit to reflect that there is also GPU support for Windows and removed the old JNI CUDA update sites.

Would be great to also test Windows 10.

**Comment by WillGiang** [comment]
Hi, the CSBDeep Fiji plugin works on Win10, CUDA 9.0, CuDNN 7.4.2, with the update site.

**Comment by lacan** [comment]
Hi all,

I'm running CARE using CUDA 10.0 and CUDNN 7.6.0 and getting `tensorflow_jni.dll` from https://www.tensorflow.org/install/lang_java

Works like a charm!

Oli

**Comment by Zhihengfeng0615** [comment]
Installing TensorFlow GPU native libraries on Windows. I meet some troubles:
![image](https://user-images.githubusercontent.com/27288257/61605752-87bf6b00-ac79-11e9-8e37-0769b3a84ff0.png)
I really need your help.

**Comment by Zhihengfeng0615** [comment]
I have solved this problem by changing "https" to "http", it works "http://sites.imagej.net/CSBDeep-GPU-win64-TF1.12.0"

**Comment by Zhihengfeng0615** [comment]
Sorry, I have new problem: I have already install "tensorflow_jni.dll" for fiji. But tensorflow still doesn't work. I'm so confused.
![image](https://user-images.githubusercontent.com/27288257/61606787-817fbd80-ac7e-11e9-9aaa-c627f91e2187.png)

**Comment by fjug** [comment]
@frauzufall Help?!
